version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: 
      - "/"
      - "/tools/credential-scanning"
      - "/tools/sbom-aggregation"
      - "/tools/fork-support"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories: 
      - "/"
      - "/tools/credential-scanning"
      - "/tools/conventional-commits/repository-ruleset"
    target-branch: "develop"
    schedule:
      interval: "weekly"
