# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Credential Scan

on:
  pull_request:
  workflow_dispatch:

jobs:

  check-for-credentials:
    runs-on: ubuntu-latest
    container: trufflesecurity/trufflehog:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # full history so we can resolve SHAs

      - name: Mark workspace as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Resolve base SHA
        id: base
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          git fetch origin "$DEFAULT_BRANCH" --quiet
          echo "sha=$(git merge-base HEAD origin/"$DEFAULT_BRANCH")" >> $GITHUB_OUTPUT

      # Manual CLI scanning is done here to allow for more flexible configuration and not pipe raw result output to GitHub Actions logs
      - name: Scan for credentials
        env:
          BASE_SHA: ${{ steps.base.outputs.sha }}
        run: >
          trufflehog git file://./ --only-verified
          --since-commit "$BASE_SHA"
          --branch HEAD --no-update --fail > /dev/null